import Head from 'next/head'
import NavBar from './components/NavBar'
import HomePage from './components/HomePage'
import About from './components/About'
import IccGang from './components/IccGang'
import Contact from './components/contact'
import Footer from './components/Footer'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
       <NavBar/>
       <HomePage/>
       <About/>
       <IccGang/>
       <Contact/>
       <Footer/>
      </main>
    </div>
  )
}
